[package]
name = "anthill-ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.56"
tokio = { version = "1.19.2", features = ["sync", "rt"] }

thiserror = "1.0.31"

vec_map = "0.8.2"
indexmap = "1.9.1"

crossbeam = "0.8.1"